services:
  authentication:
    container_name: authentication
    build: ./authentication
    image: authentication:fastify
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      - database
    environment:
      - PORT=${AUTH_PORT}
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
    profiles:
      - authentication
      - backend
      - development

  database:
    container_name: database
    build: ./database
    image: database:sqlite
    volumes:
      - db-sqlite:/data/sqlite:rw,z
    environment:
      - PORT=${DB_PORT}
    env_file:
      - .env
    networks:
      - transcendence
    ports:
      - "${DB_PORT}:1919"
    restart: always
    profiles:
      - authentication
      - backend
      - development

volumes:
  db-sqlite:
    driver: local
    driver_opts:
      type: none
      device: ../data/ft_transcendence/sqlite
      o: bind

networks:
  transcendence:
    driver: bridge
    name: transcendence