services:
  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx:transcendence
    ports:
      - 4242:443
    depends_on:
      - authentication
      - usermanagement
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
    profiles:
      - frontend
      - backend
      - development
  
  authentication:
    container_name: authentication
    build: ./authentication
    image: authentication:fastify
    depends_on:
      - database
    environment:
      - PORT=${AUTH_PORT}
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
    profiles:
      - authentication
      - backend
      - development

  database:
    container_name: database
    build: ./database
    image: database:sqlite
    volumes:
      - db-sqlite:/data/sqlite:rw,z
    environment:
      - PORT=${DB_PORT}
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
    profiles:
      - authentication
      - backend
      - development
  usermanagement:
    container_name: user_management
    build: ./user_management
    image: user_management:fastify
    depends_on:
      - database
    environment:
      - PORT=${USER_PORT}
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
    profiles:
      - authentication
      - backend
      - development

  chat:
    container_name: chat
    build: ./chat
    image: chat:fastify
    depends_on:
      - database
    environment:
      - PORT=${CHAT_PORT}
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
    profiles:
      - authentication
      - backend
      - development

volumes:
  db-sqlite:
    driver: local
    driver_opts:
      type: none
      device: ../data/ft_transcendence/sqlite
      o: bind

networks:
  transcendence:
    driver: bridge
    name: transcendence
