services:
  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx:transcendence
    ports:
      - 4242:443
    depends_on:
      - authentication
      - usermanagement
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
    profiles:
      - backend
      - development
  
  authentication:
    container_name: authentication
    build: ./authentication
    image: authentication:fastify
    depends_on:
      - database
    environment:
      - PORT=${AUTH_PORT}
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
    profiles:
      - authentication
      - backend
      - development

  database:
    container_name: database
    build: ./database
    image: database:sqlite
    depends_on:
      - rabbitmq
    volumes:
      - db-sqlite:/data/sqlite:rw,z
    environment:
      - PORT=${DB_PORT}
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
    profiles:
      - authentication
      - backend
      - development

  usermanagement:
    container_name: user_management
    build: ./user_management
    image: user_management:fastify
    depends_on:
      - database
    environment:
      - PORT=${USER_PORT}
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
    profiles:
      - authentication
      - backend
      - development

  chat:
    container_name: chat
    build: ./chat
    image: chat:fastify
    depends_on:
      - database
    environment:
      - PORT=${CHAT_PORT}
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
    profiles:
      - authentication
      - backend
      - development

  games:
    container_name: games
    build: ./games
    image: games:fastify
    depends_on:
      - database
    environment:
      - PORT=${GAMES_PORT}
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
    profiles:
      - game
      - backend
      - development
      
  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend:typescript
    command: ["npm", "run", "build"]
    volumes:
      - frontend_dist:/app/dist
    networks:
      - transcendence
    profiles:
      - build
      - frontend
  
  backend:
    container_name: backend
    build: ./backend
    image: backend:typescript
    volumes:
      - frontend_dist:/app/dist
    environment:
      - PORT=${BACKEND_PORT}
    networks:
      - transcendence
    profiles:
      - build
      # - frontend

  # gamestate:
  #   container_name: gamestate
  #   build: ./gamestate
  #   image: gamestate:fastify
  #   depends_on:
  #     - database
  #   environment:
  #     - PORT=${GAMESTATE_PORT}
  #   ports:
  #     - ${GAMESTATE_PORT}:${GAMESTATE_PORT}
  #   env_file:
  #     - .env
  #   networks:
  #     - transcendence
  #   restart: always
  #   profiles:
  #     - game
  #     - backend
  #     - development

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status", "-q"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - transcendence
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    profiles:
      - backend
      - development

volumes:
  db-sqlite:
    driver: local
    driver_opts:
      type: none
      device: ../data/ft_transcendence/sqlite
      o: bind
  frontend_dist:
    driver: local
    driver_opts:
      type: none
      device: ../data/ft_transcendence/frontend
      o: bind
  rabbitmq_data:
    driver: local
    driver_opts:
      type: none
      device: ../data/ft_transcendence/rabbitmq
      o: bind

networks:
  transcendence:
    driver: bridge
    name: transcendence
