'use strict'

const fp = require('fastify-plugin')

module.exports = fp(async function schemaLoaderPlugin (fastify, opts) {
  fastify.addSchema(require('./createUser.json'))
  fastify.addSchema(require('./user.json'))
  fastify.addSchema(require('./getUser.json'))
  fastify.addSchema(require('./userProfile.json'))
  fastify.addSchema(require('./getProfile.json'))
  fastify.addSchema(require('./avatar.json'))
  fastify.addSchema(require('./getAvatar.json'))
  fastify.addSchema(require('./updatePassword.json'))
  fastify.addSchema(require('./updateUser.json'))
  fastify.addSchema(require('./getUserByUsername.json'))
  fastify.addSchema(require('./addFriend.json'))
  fastify.addSchema(require('./respondFriendRequest.json'))
  fastify.addSchema(require('./userFriends.json'))
  fastify.addSchema(require('./removeFriend.json'))
  fastify.addSchema(require('./createOAuthUser.json'))
  fastify.addSchema(require('./OAuthGetUser.json'))
  fastify.addSchema(require('./setMfa.json'))
  fastify.addSchema(require('./mfaType.json'))
  fastify.addSchema(require('./userId.json'))
  fastify.addSchema(require('./mfaToken'))
})
