name: Integration

on:
  pull_request:
    branches: [main]

jobs:
  check-pull-request:
    name: Check Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PR Title
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '\[(FEATURE|FIX|DOCUMENTATION|STYLE|TEST|DEVOPS|REFRACTOR|REVERT)\] .+$'
          error: 'Pull-Request should start with type "[FIX]".'
          excludeDescription: 'true' 
          excludeTitle: 'false'  
          checkAllCommitMessages: 'false'  

      - name: Check PR Body
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '[\s\S]{10,}'
          error: 'Pull-Request body should be at least 10 characters long.'
          excludeDescription: 'false'
          excludeTitle: 'true'
          checkAllCommitMessages: 'false'

      - name: Check Commit Message
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(FEATURE|FIX|DOCUMENTATION|STYLE|TEST|DEVOPS|REFACTOR|REVERT): .+|^Merge pull request #[0-9]+ from [\w\-]+\/[\w\-].*'
          error: '<PR type>: <description>".'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'false'
